name: ngdart
description: >-
  Fast and productive web framework by Google.
  Separate, but similar to the JavaScript framework with a similar name.
version: 8.0.0-dev.4
repository: https://github.com/angulardart-community/angular

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: 5.13.0 #5.12.0
  build: ^2.4.0
  built_collection: ^5.1.1
  build_modules: '>=4.0.7 < 6.0.0'
  built_value: ^8.4.3
  collection: ^1.18.0
  intl: ^0.18.0
  js: ^0.6.5
  meta: ^1.11.0  
  stream_transform: ^2.1.0
  source_gen: 1.4.0 #1.2.6
  source_span: 1.10.0
  mockito: any
  charcode: ^1.3.1 #updated
  string_scanner: ^1.2.0 #updated
  args: 2.3.2
  code_builder: 4.5.0
  csslib: 0.17.2
  dart_style: 2.2.4 
  logging: 1.1.0
  path: 1.8.3
  package_config: 2.1.0
  
dev_dependencies:
  async: ^2.10.0
  build_runner: 2.4.6
  build_test: 2.2.1
  build_web_compilers: 4.0.6
  lints: ^2.0.1
  #mockito: 5.4.2  
  test: ^1.22.2
