name: goldens
description: Goldens for AngularDart.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  js: ^0.6.5
  ngdart: #^8.0.0-dev.1
    path:
      ../ngdart


dev_dependencies:
  build_runner: 2.4.6 
  build_web_compilers: 4.0.6
  dart_style: ^2.2.4
  glob: ^2.1.1
  lints: ^2.0.1
  path: ^1.8.3
