name: ngforms
description: >
  Forms framework for AngularDart.
  Easily create forms to accept input from users.
version: 5.0.0-dev.2
repository: https://github.com/angulardart-community/angular

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.11.0
  ngdart: #^8.0.0-dev.1
    path:
      ../ngdart
    

dev_dependencies:
  build_runner: 2.4.6
  build_test: 2.2.1
  build_web_compilers: 4.0.6
  lints: ^2.0.1
  mockito: 5.4.2 
  ngtest: #^5.0.0-dev.1
    path:
      ../ngtest

  test: ^1.22.2
